build:
	 g++ -std=c++11 -O3 -pthread -o  app main.cpp  server.cpp poll.cpp socket.cpp httpParser.cpp;
	@echo "Build App Done"
debug:
	g++ -std=c++11 -g -pthread -o  appdebug main.cpp  server.cpp poll.cpp socket.cpp httpParser.cpp;